CONFIGURE_SOURCES_CANVAS = "source-canvas"
CONFIGURE_SOURCES_BUTTON = "config-sources-button"
N_SOURCES_INPUT = "number-sources-input"
SOURCE_TYPE_DROPDOWN_CONTAINER="source-type-dropdown-container"
SAVE_CONIG_BUTTON = 'save-config-button'
SOURCE_TYPES = 'source-type-selectors'
CONFIG_DISPLAY = 'config-display'
CANVAS_ALERT = 'canvas-alert'
INPUTS_DIV='inputs-div'
CALCULATE_BUTTON='calculate-button'
RESULTS_DIV = 'results-div'
WF_INPUT = 'wfinput'
F_INPUT = 'finput'
IMPACT_INPUT_SEL='impSEL'
IMPACT_INPUT_PEAK='impPEAK'
IMPACT_INPUT_RMS='impRMS'
IMPACT_INPUT_RANGE='impRANGE'
IMPACT_INPUT_NPILES='impNPILES'
IMPACT_INPUT_NSTRIKES='impNSTRIKES'

DTH_INPUT_SEL='dthSEL'
DTH_INPUT_PEAK='dthPEAK'
DTH_INPUT_RMS='dthRMS'
DTH_INPUT_RANGE='dthRANGE'
DTH_INPUT_NPILES='dthNPILES'
DTH_INPUT_RATE='dthRATE'
DTH_INPUT_TIME='dthTIME'


VIBRATORY_INPUT_RMS='vibRMS'
VIBRATORY_INPUT_RANGE='vibRANGE'
VIBRATORY_INPUT_NPILES='vibNPILES'
VIBRATORY_INPUT_TIME='vibTIME'